/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface JdSideDrawer {
        "closeMe": () => Promise<void>;
        "headerTitle": string;
        "open": boolean;
        /**
          * Developers should try to rely on publicly exposed methods as little as possible, and instead default to using properties and events as much as possible. As an app scales, we've found it's easier to manage and pass data through @Prop rather than public methods.
         */
        "openMe": () => Promise<void>;
    }
}
declare global {
    interface HTMLJdSideDrawerElement extends Components.JdSideDrawer, HTMLStencilElement {
    }
    var HTMLJdSideDrawerElement: {
        prototype: HTMLJdSideDrawerElement;
        new (): HTMLJdSideDrawerElement;
    };
    interface HTMLElementTagNameMap {
        "jd-side-drawer": HTMLJdSideDrawerElement;
    }
}
declare namespace LocalJSX {
    interface JdSideDrawer {
        "headerTitle"?: string;
        "open"?: boolean;
    }
    interface IntrinsicElements {
        "jd-side-drawer": JdSideDrawer;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "jd-side-drawer": LocalJSX.JdSideDrawer & JSXBase.HTMLAttributes<HTMLJdSideDrawerElement>;
        }
    }
}
